name: Run action

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: r-lib/actions/setup-r@v2
      with:
        r-version: '3.5.3' # The R version to download (if necessary) and use. 
    # Use "renv" to retrieve R version recorded in renv.lock file.
    - run: Rscript -e 'print("hello")'
