name: Run action

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      
    - name: Build the Docker image
      run: docker build -t image .

      
    - name: Docker Run Action
      run: >
        docker run --rm --name container -v 
        /github/workspace/shared_folder:/home/graphs/shared_folder:rw 
        image

    - name: List Directory Contents
      run: ls -R /github/workspace/shared_folder/


    - uses: actions/upload-artifact@v3
      with:
        name: output_${{ github.sha }}
        path: /github/workspace/shared_folder/

