name: Run action

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      
    - name: Build the Docker image
      run: docker build -t chickens_image .


    - name: List Directory Contents
      run: ls -R /github/workspace/shared_folder/

      
    - name: Docker Run Action
      run: >
        docker run --rm --name chicken_coop -v 
        /github/workspace/shared_folder:/home/chickens/shared_folder:rw 
        chickens_image


    - uses: actions/upload-artifact@v3
      with:
        name: chicken_output_${{ github.sha }}
        path: /github/workspace/shared_folder/

